# Generated by Django 4.1.3 on 2022-11-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bb",
            name="published",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
